/* ══════════ FREE EXPRESSION AT VANDERBILT · narration ══════════
   One clip per page (<page>/1), plus one per situation on the scenarios
   page. The screen keeps the headline, the activity, and the policy
   facts; the narration carries the why. Until MP3s are recorded into
   assets/audio/fe/, the Listen button reads these words with the
   browser's own voice. No em or en dashes. */
window.FE_NARR = {
  'home/1': 'Welcome to Free Expression at Vanderbilt. A university does its best work when people can meet competing ideas, question assumptions, disagree openly, and take part in rigorous inquiry. Staff help make that possible, often in ways nobody notices. Over six short lessons you will look at why free expression matters here, the three principles behind it, what time, place, and manner rules mean in practice, and what your role is when expression shows up in your space. Each page has one thing to do. Tap Begin when you are ready.',

  'tradition/1': 'Vanderbilt did not discover free expression last year. Tap through the timeline. The university was founded after the Civil War with a stated aspiration of strengthening the ties between all sections of a divided country. In 1967, during the Civil Rights Movement, students invited speakers the state legislature wanted kept off campus, and the chancellor held to an open forum. Today the university is investing again in open inquiry, dialogue, and civil discourse, at a time of real polarization. The thread through all of it: ideas get debated here, and differences get bridged.',

  'commitment/1': 'Here is the heart of it. The commitment is not merely to allow disagreement. It is to maintain an environment where disagreement and intellectual exploration can actually happen. For staff, that is an institutional responsibility: helping preserve the conditions for that work, even when the ideas are controversial, unpopular, or contested. This training uses three principles: free expression, open forums, and civil discourse. They are not separate commitments. Together they describe the community Vanderbilt wants to be, and the shared job of sustaining it. Open each one.',

  'expression/1': 'Free expression is the freedom to express, examine, question, and challenge ideas, including ideas others find disagreeable or offensive. For students and faculty, it is how learning and scholarship work: asking hard questions, testing competing explanations, building new ideas. When people meet ideas they reject, Vanderbilt’s policy points them toward discussion, debate, and respectful dialogue rather than suppression. Hold on to one key concept. Protecting expression is not the same as endorsing it. You can keep the room open for an idea you disagree with, and so can the university. Try four moments on the right.',

  'forums/1': 'An open forum is any space or opportunity where different ideas can be presented, questioned, debated, and tested. Some are formal: lectures, debates, speaker programs, dialogue programs like Dialogue Vanderbilt and 250 Conversations on America. Some are everyday: a classroom conversation, a student organization meeting, an informal talk across difference. Peaceful demonstrations and counterexpression count too. Tap the forums you have seen or supported. Then take a minute with the reflection: where does your area create chances for students to meet a different perspective?',

  'civil/1': 'Civil discourse is effective, respectful dialogue across difference. Notice what it does not require. It does not require agreement, consensus, or avoiding hard topics. It does not ask anyone to hide strongly held views or pretend differences are not there. It is a way to engage disagreement productively. The Community Creed puts it in Vanderbilt words: curiosity and humility, the courage to challenge assumptions, openness, and respect. Sort the eight cards. Some are habits staff can model. Some are things civil discourse never asked for.',

  'role/1': 'Staff play an essential role in the conditions that let learning, teaching, research, and the exchange of ideas flourish. That job is not to make everyone agree, or to make every conversation comfortable. It is to help students and faculty ask difficult questions, encounter unfamiliar ideas, disagree, challenge arguments, and engage each other with dignity, while everyone can still take part in university life without disruption. What staff can do best is model it: curiosity over assumption, questions over declarations, consistency in applying the rules, de-escalation over confrontation, and respect for expression with clear boundaries on conduct. Five moments on the right.',

  'myths/1': 'Five misconceptions come up again and again. For each card, make your call first: myth, or true? Then flip it for the reality. A hint before you start: every one of these sounds reasonable, and every one of them gets something important wrong.',

  'question/1': 'This is the most useful idea in the course. Free expression and reasonable rules about conduct can coexist. Vanderbilt protects demonstrations, protests, counterprotests, and dissent as valued forms of expression, and it sets rules about the time, place, and manner of expression so the university can keep doing its work and everyone can exercise their own rights. So when you see expressive activity, the question is not whether you agree with the message. The question is whether it is happening in a way that is consistent with policy and lets others keep speaking, listening, teaching, learning, and taking part. Then, name the four kinds of expression Vanderbilt distinguishes.',

  'tpm/1': 'Time, place, and manner. Time is about when and for how long: plans submitted at least forty eight hours ahead when possible, a recommended limit of three hours, never more than seven and a half, and no overnight gatherings. Place is about where: some spaces, like private offices, labs, classrooms in session, health facilities, and the Medical Center, are off limits, and entrances, exits, and walkways stay clear. Manner is about how: signs, picketing, marching, and symbolic expression are welcome, while blocking doors, drowning out a speaker, or causing harm are not. Open each one and answer its question.',

  'context/1': 'Context matters. A demonstration that stands on its own can generally be loud: speeches, chanting, marching, signs. A protest aimed at an ongoing event is different, because two sets of rights share the same space. Protesters may picket, hold signs, turn their backs, or cover their ears. Audible activity can be restricted when it would interfere with the event. The goal is to preserve both the right to protest and the right of others to speak, listen, participate, and learn. Try six things you might see at a protest of a speaker event.',

  'policies/1': 'Nobody expects you to memorize the rules. Expect yourself to know where they live. The Freedom of Expression Policy is the primary one. Use of University Space covers reservations, events, notices, and outdoor use. The Excessive Noise and Amplified Sound Policy covers noise. And installations, the symbolic structures and displays, fall under Use of University Space. Match four requests to the right policy.',

  'staffrole/1': 'So what is your role? Not to be a policy expert, and not to rule on protests. Focus on conduct, not viewpoint. Do not assume that controversy or offense means a policy violation. Ask whether people can still enter, hear, participate, work, and move safely. Do not try to resolve a protest on your own if it is outside your role. Know your contact, follow the direction of designated officials, and avoid making things worse. Sort what you notice: is it about the viewpoint, or about conduct?',

  'scenarios/1': 'Now put it together. One controversial speaker, three moments: the complaint before the event, a protest outside the door, and a disruption inside the room. Choose a response in each and see where it leads.',
  'scenarios/s1': 'Students tell you another student group has invited a speaker whose views are offensive, and they ask you to get the event canceled. What do you say?',
  'scenarios/s2': 'The night of the event, students stand outside holding signs opposing the speaker. Nobody is blocking the entrance, and attendees walk in without trouble. Is the fact that the protest targets this event a policy problem?',
  'scenarios/s3': 'During the talk, protesters shout again and again, so the speaker cannot be heard and the audience cannot take part. What has changed?',

  'quiz/1': 'Five questions, one at a time, with an explanation after each. Four of five finishes the check, and you can retake it.',

  'practice/1': 'From principle to practice. Pick one of the five questions that fits your work best: making room for questions, modeling curiosity when you disagree, helping students meet different perspectives, telling discomfort from disruption, or supporting expression while holding a line on conduct. Then write one concrete move you will make in your role. Commit to it, and if it helps, copy the message and share it with your team.',

  'learn/1': 'Free expression at Vanderbilt is not simply a policy to know. It is a culture the community has a responsibility to sustain. For staff, that means helping students encounter ideas, ask difficult questions, disagree, listen, and reach their own conclusions, while everyone else can keep learning, speaking, and taking part. The resources here are worth bookmarking. Thank you for the work you do to keep the room open.'
};
